version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      # Use environment variable BACKEND_URL if provided, otherwise use service name
      - BACKEND_URL=${BACKEND_URL:-http://backend:8000}
    depends_on:
      - backend
    networks:
      - voice-matching-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-west-2}
    volumes:
      - ./backend:/app  # Development mode hot-reload
    networks:
      - voice-matching-network

networks:
  voice-matching-network:
    driver: bridge
